---
title: "Fairmont"
author: "Hannah Garcia-Wickstrum"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(here)
library(stargazer)
```


```{r}
### Fairmont Temperature: 1912-2019
### Number of Missing Years: 13

fairmont_temp <- read_csv(here::here("csv_files",
                                     "temperature",
                                     "Fairmont_temperature.csv")) %>%
  clean_names()

# -----------------------------------------

# Statistics (linear regression (lm)) for mean, max, and min temperatures in Fairmont

## Mean model (lm)
meantemp_lm <- lm(mean_f ~ year_s, data=fairmont_temp)
summary(meantemp_lm)
# stargazer(meantemp_lm, type = "text")
# Formula: mean = 0.024386*(year) + 12.723140
# R^2: 0.1458 
# p-value: 7.94e-05 (p < 0.001) Significant

## Max model (lm)
maxtemp_lm <- lm(max_f ~ year_s, data=fairmont_temp)
summary(maxtemp_lm)
# stargazer(maxtemp_lm, type ="text")
# Formula: max = 0.032428*(year) + 7.330187
# R^2: 0.2008
# p-value: 3.139e-06 (p < 0.01) Significant

## Min model (lm)
mintemp_lm <- lm(min_f ~ year_s, data=fairmont_temp)
summary(mintemp_lm)
# stargazer(mintemp_lm, type = "text")
# Formula: min = 0.015996*(year) + 18.780501
# R^2: 0.058
# p-value: 0.01086 (p < 0.05) Significant

# --------------------------------------------
# Create graph of averages (mean, max, and min)

fairmont_temp_graph <- ggplot(data=fairmont_temp,
                              aes(x=year_s)) +
  geom_line(aes(y=mean_f),
            color="black") +
  geom_line(aes(y=max_f),
            color="black") +
  geom_line(aes(y=min_f),
            color="black") +
  geom_point(aes(y=mean_f),
             color="black",
             pch=18,
             size=1.5) +
  geom_point(aes(y=max_f),
             color="darkred",
             pch=15,
             size=1.5) +
  geom_point(aes(y=min_f),
             color="gold",
             pch=17,
             size=1.5) +
  labs(x="Years", 
       y="Degrees Farenheit",
       title="Fairmont") +
  scale_x_continuous(limits=c(1920, 2020),
                     breaks=seq(1920,2020,10),
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(45,80),
                     breaks=seq(45,80,5),
                     expand=c(0,0)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) 
  # geom_smooth(method='lm',
  #             formula= y~x,
  #             se=FALSE,
  #             color= "black",
  #             size=0.5)

# ggpubr::stat_regline_equation(aes(y=mean_f,x=year_s), output.type = "expression") 

fairmont_temp_graph

```

```{r}
# Change in temperature
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1922
# final year: 2019

# -----------------------------------
# Mean temperature change: 2.365442

x_variable_mean <- 0.024386
intercept_mean <- 12.723140

mean_temp_change <- (((2019)*x_variable_mean) + intercept_mean) - (((1922)*x_variable_mean) + intercept_mean)

mean_temp_change

# --------------------------------
# Max temperature change: 3.145516

x_variable_max <- 0.032428
intercept_max <- 7.330187
max_temp_change <- (((2019)*x_variable_max) + intercept_max) - (((1922)*x_variable_max) + intercept_max)
max_temp_change

# -------------------------------
# Min temperature change: 1.551612

x_variable_min <- 0.015996
intercept_min <- 18.780501
min_temp_change <- (((2019)*x_variable_min) + intercept_min) - (((1922)*x_variable_min) + intercept_min)
min_temp_change
```


```{r}
# Playing with data
# fairmont_temp_demo <- fairmont_temp %>%
#   pivot_wider()

# Graph of just one line + statistics (Test)
# Fairmont mean temperature

fairmont_meantemp_graph <- ggplot(data=fairmont_temp,
                                  aes(x=year_s,
                                      y=mean_f)) +
  geom_line(color="black") +
  geom_point(color="black",
             pch=18,
             size=1.5) +
  scale_x_continuous(limits=c(1920, 2020),
                     breaks=seq(1920,2020,10),
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(45,80),
                     breaks=seq(45,80,5),
                     expand=c(0,0)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method='lm',
              formula= y~x,
              se=FALSE,
              color= "black",
              size=0.5) +
  ggpubr::stat_regline_equation(aes(y=mean_f,
                                    x=year_s),
                                output.type = "expression")


fairmont_meantemp_graph

```



```{r}
# Fairmont Precipitation: 1916-2019
# Number of Years Missing: 20

fairmont_precip <- read_csv(here::here("csv_files",
                                       "precipitation",
                                       "fairmont_precip.csv"))

# --------------------------------------

# Fairmont Statistics - Precipitation

fairmontprecip_lm <- lm(annualgrowingseason ~ year, data=fairmont_precip)
summary(fairmontprecip_lm)
# p-value = 0.4188 Not Significant

# ----------------------------------------

fairmont_precip_graph <- ggplot(data=fairmont_precip,
                                aes(x=year,
                                    y=annualgrowingseason)) +
  geom_line(color="blue") +
  geom_point(color="blue",
             pch=18,
             size=1.5) +
  labs(x="Growing Season (year)",
       y="Precipitation (inches)",
       title="Fairmont") +
  scale_x_continuous(limits=c(1915, 2020),
                     breaks=seq(1915,2020,10),
                     expand=c(0,1)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
                    "precipitation",
                    "fairmont_precipitation_graph.png"))

fairmont_precip_graph
```

```{r}
## Fairmont 5-yr CV precipitation 

# --------------------------------
# Statistics for 5-yr cv

fairmont_5yr_lm <- lm(x5yr_cv ~ year, data=fairmont_precip)
summary(fairmont_5yr_lm)
# p-value: p-value: 6.6e-06 (p < 0.001) - Significant

# --------------------------------
# Graph of Fairmont 5-yr CV precipitation

fairmont_5yr_graph <- ggplot(data=fairmont_precip,
                                aes(x = year,
                                    y = x5yr_cv)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (year)",
       y="5 yr CV in annual growing season precipitation",
       title="Fairmont") +
  scale_x_continuous(limits=c(1915, 2020),
                     breaks=seq(1915,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method='lm',
              formula= y~x,
              se=FALSE,
              color= "black",
              size=0.5) +
  annotate("text", x = 1995, y = 0.25,
           label = "CV = 0.003*(year) - 5.4853") +
  annotate("text", x = 1995, y = 0.20, 
           label = "p-value < 0.001, R2=0.211") +
  ggsave(here::here("report_graphs",
                    "5yr_cv",
                    "fairmont_5yr_cv_graph.png"))
  
fairmont_5yr_graph
```



```{r}
# Fairmont Snowfall

fairmont_snowfall <- read_csv(here::here("csv_files",
                                         "snowfall",
                                         "fairmont_snowfall.csv"))
# ---------------------------------

# Fairmont Snowfall Statistics

fairmont_snowfall_lm <- lm(total ~ year, data=fairmont_snowfall)
summary(fairmont_snowfall_lm)

# p-value = 0.07512 NOT Significant

# --------------------------------

# Graph of Snowfall - the year 1979 says 49 inches of snowfall, but the previous report doesn't have a datapoint that large...

fairmont_snowfall_graph <- ggplot(data=fairmont_snowfall,
                                  aes(x=year,
                                      y=total)) +
  geom_line(color="blue") +
  geom_point(color="blue",
             size=1.5) +
  labs(x="Year",
       y="Snowfall (inches)",
       title="Fairmont") +
  scale_x_continuous(limits=c(1946, 2011),
                     breaks=seq(1946,2011,10),
                     expand=c(0,1)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
             "snowfall",
             "Fairmont_Snowfall.png"))

fairmont_snowfall_graph

```


