---
title: "Idyllwild Climate"
author: "Hannah Garcia-Wickstrum"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(here)
```

```{r}
# Idyllwild Temperature: 1946-2019
# Number of Missing Years: 3

idyllwild_temp <- read_csv(here::here("csv_files",
                                      "temperature",
                                      "idyllwild_temp.csv")) %>%
  clean_names()

# ------------------------------------------
# Statistics (linear regression (lm)) for mean, max, and min temperature in Idyllwild

## Mean model (lm)
meantemp_lm <- lm(mean ~ year, data=idyllwild_temp)  
summary(meantemp_lm)
# p-value: 2.678x10^-09 = Significant

## Max model (lm)
maxtemp_lm <- lm(max ~ year, data=idyllwild_temp)
summary(maxtemp_lm)
# p-value: 0.6608 = NOT Significant

## Min model (lm)
mintemp_lm <- lm(min ~ year, data=idyllwild_temp)
summary(mintemp_lm)
# p-value: < 2.2x10^-16 = Significant

# ----------------------------------------
# Graph of Idyllwild mean and min temperature (Max is not significant)

idyllwild_temp <- idyllwild_temp %>%
  pivot_longer('mean':'min',
               names_to = "temp_average",
               values_to = "value")

idyllwild_temp_graph <- ggplot(data=idyllwild_temp, 
                              aes(x=year, y=value, 
                                  col=temp_average)) +
  theme_minimal() +
  geom_line() +
  geom_point() +
  geom_smooth(data=subset(idyllwild_temp,
                          temp_average=="mean"|temp_average=="min"),
              method="lm", 
              se=FALSE,
              size=0.65) +
  labs(x="Year",
       y="Degrees Farenheit", 
       title="Idyllwild") +
  theme(plot.title = element_text(hjust = 0.5), 
        legend.position = "none") +
  scale_x_continuous(limits=c(1945, 2021),
                     breaks=seq(1945,2021,10),
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(30,75),
                     breaks=seq(30,75,5),
                     expand=c(0,0)) +
  annotate("text", x = 1965, y = 57.5,
           label = "mean: p-value < 0.001
           slope=0.04646",
           size=3) +
  annotate("text", x = 1965, y = 45,
           label = "min: p-value < 0.001
           slope=9.028e-02",
           size=3) +
  ggsave(here::here("report_graphs",
                    "temperature",
                    "idyllwild_temperature_graph.png"),
          height=5,
         width=7,
         units="in")

idyllwild_temp_graph
```



```{r}
# Change in temperature
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1946
# final year: 2019

# -----------------------------------
# Mean temperature change: 3.39158

x_variable_mean <- 0.04646
intercept_mean <- -38.90670

mean_temp_change <- (((2019)*x_variable_mean) + intercept_mean) - (((1946)*x_variable_mean) + intercept_mean)

mean_temp_change

# -------------------------------
# Min temperature change: 6.59044

x_variable_min <- 9.028e-02
intercept_min <- -1.409e+02
min_temp_change <- (((2019)*x_variable_min) + intercept_min) - (((1946)*x_variable_min) + intercept_min)
min_temp_change
```



```{r}
# Idyllwild Precipitation: 1948-2019
# Number of Missing Years: 5

# Read in .csv file
idyllwild_precip <- read_csv(here::here("csv_files",
                                        "precipitation",
                                        "idyllwild_precip.csv")) %>%
  clean_names()
                      
# -----------------------------------

# Statistics for Idyllwild Precipitation (Used growing season instead of total)

idyllwildprecip_lm <- lm(annual_growingseason ~ years, data=idyllwild_precip)
summary(idyllwildprecip_lm)
# p-value: 0.9986 = NOT Significant

# -----------------------------------

# Graph of Precipitation (annual - inches)

idyllwild_precip_graph <- ggplot(data=idyllwild_precip, 
                                 aes(x=years, 
                                     y=annual_growingseason)) +
  geom_point(pch=18, color="blue") +
  geom_line(color="blue") +
  theme_minimal() +
  labs(title= "Idyllwild",
       x= "Growing Season (year)", 
       y= "Precipitation (inches)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(limits=c(1945, 2020), 
                     breaks=seq(1945,2020,10), 
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(10,60), 
                     breaks=seq(10,60,10), 
                     expand=c(0,0)) +
  ggsave(here::here("report_graphs",
                    "precipitation",
                    "idyllwild_precip_graph.png"))

idyllwild_precip_graph
```

```{r}
#  Idyllwild 5-yr CV Precipitation

# -----------------------------
# Statistics for 5-yr cv

idyllwild_5yr_lm <- lm(x5yr_cv ~ years, data = idyllwild_precip)
summary(idyllwild_5yr_lm)
# p-value: 0.7411 - NOT Significant

# -------------------------------
# Graph of 5-yr CV

idyllwild_precip_cv_graph <- ggplot(data=idyllwild_precip, 
                                    aes(x=years, 
                                        y=x5yr_cv)) +
  geom_point(pch=18, color="blue") +
  geom_line(color="blue") +
  theme_minimal() +
  labs(title= "Idyllwild",
       x= "Growing Season (year)", 
       y= "5 yr CV in annual growing season precipitation") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(limits=c(1945, 2020), 
                     breaks=seq(1945,2020,10), 
                     expand=c(0,1)) +
  ggsave(here::here("report_graphs",
                    "5yr_cv",
                    "idyllwild_5yr_cv_graph.png"))

idyllwild_precip_cv_graph
```



```{r}
# Idyllwild Snowfall
# read in csv

idyllwild_snow <- read_csv(here::here("csv_files",
                                      "snowfall",
                                      "idyllwild_snowfall_edit.csv"))

# ---------------------------------------
# Statistics
idyllwild_snow_lm <- lm(annualgrowingseason ~ years, data=idyllwild_snow)
summary(idyllwild_snow_lm)
# p-value: 0.09413 - NOT Significant
# x-variable: -0.2328
# Intercept: 497.6539

# ---------------------------------------
idyllwild_snowfall_graph <- ggplot(data=idyllwild_snow,
                                   aes(x=years,
                                       y=annualgrowingseason)) +
  geom_point(pch=18, color="blue") +
  geom_line(color="blue") +
  theme_minimal() +
  labs(title= "Idyllwild", 
       x= "Water Year",
       y= "Snowfall (inches)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
                    "snowfall",
                    "idyllwild_snowfall_graph.png"))

idyllwild_snowfall_graph
```

