---
title: "Mt. Wilson No. 2"
author: "Hannah Garcia-Wickstrum"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(here)
library(stargazer)
```

```{r}
# Mt. Wilson No. 2 Temperature: 1949-2017
# Number of Missing Years: 3

mtwilson_temp <- read_csv(here::here("csv_files",
                                     "temperature",
                                     "mtwilsonno2.csv")) %>%
  clean_names()

# -----------------------------------------
# Statistics (lm) for mean, max, and min temperature at Mt. Wilson No. 2

# Mean model (lm)
meantemp_lm <- lm(mean ~ year, data = mtwilson_temp)
summary(meantemp_lm)
# p-value: 1.179 x 10^-12 = Significant

# Max model (lm)
maxtemp_lm <- lm(max ~ year, data = mtwilson_temp)
summary(maxtemp_lm)
# p-value: 2.279 x 10^-14 = Significant

# Min model (lm)
mintemp_lm <- lm(min ~ year, data = mtwilson_temp)
summary(mintemp_lm)
# p-value: 4.464 x 10^-7 = Significant

# ------------------------------------------
# Create graph of averages (mean, max, and min)

mtwilson_temp <- mtwilson_temp %>%
  pivot_longer('mean':'min',
               names_to = "temp_average",
               values_to = "value")

mtwilson_temp_graph <- ggplot(data=mtwilson_temp, 
                              aes(x=year, y=value, 
                                  col=temp_average)) +
  theme_minimal() +
  geom_line() +
  geom_point() +
  geom_smooth(data=mtwilson_temp,
              method="lm", 
              se=FALSE,
              size=0.65) +
  labs(x="Year",
       y="Degrees Farenheit", 
       title="Mt. Wilson No. 2") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  scale_x_continuous(limits=c(1948, 2020),
                     breaks=seq(1948,2020,10),
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(40,75),
                     breaks=seq(40,75,5),
                     expand=c(0,0)) +
  annotate("text", x = 1968, y = 60,
           label = "mean: p-value < 0.001
           slope=0.07010",
           size=3) +
  annotate("text", x = 1968, y = 42,
           label = "min: p-value < 0.001
           slope=0.046378",
           size=3) +
  annotate("text", x = 1968, y = 70,
           label = "max: p-value < 0.001
           slope=8.995e-02",
           size=3) +
  ggsave(here::here("report_graphs",
                    "temperature",
                    "mtwilson_temperature_graph.png"),
          height=5,
         width=7,
         units="in")


mtwilson_temp_graph
```

```{r}
# Change in temperature
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1949
# final year: 2017

# -----------------------------------
# Mean temperature change: 4.7668

x_variable_mean <- 0.07010
intercept_mean <- -82.18578

mean_temp_change <- (((2017)*x_variable_mean) + intercept_mean) - (((1949)*x_variable_mean) + intercept_mean)

mean_temp_change

# --------------------------------
# Max temperature change: 6.1166

x_variable_max <- 8.995e-02
intercept_max <- -1.125e+02
max_temp_change <- (((2017)*x_variable_max) + intercept_max) - (((1949)*x_variable_max) + intercept_max)
max_temp_change

# -------------------------------
# Min temperature change: 3.153704

x_variable_min <- 0.046378
intercept_min <-  -44.320519
min_temp_change <- (((2017)*x_variable_min) + intercept_min) - (((1949)*x_variable_min) + intercept_min)
min_temp_change
```



```{r}
# Mt. Wilson No. 2 Precipitation Graph

mtwilson_precip <- read_csv(here::here("csv_files",
                                       "precipitation",
                                       "mtwilsonno2_precip.csv"))
# --------------------------------------------------
# Statistics for Mt. Wilson No. 2 Precipitation

mtwilsonprecip_lm <- lm(annualgrowingseason ~ year, data=mtwilson_precip)
summary(mtwilsonprecip_lm)
# p-value: 0.5732 - NOT Significant

# ---------------------------------------------------
# Graph Mt. Wilson No. 2 Precipitation

mtwilson_precip_graph <- ggplot(data=mtwilson_precip,
                                aes(x = year,
                                    y = annualgrowingseason)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (Oct-Sept)",
       y="Precipitation (inches)",
       title="Mt. Wilson No. 2") +
  scale_x_continuous(limits=c(1945, 2020),
                     breaks=seq(1945,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
                    "precipitation",
                    "mtwilson_precip_graph.png"))


mtwilson_precip_graph

```

```{r}
# Mt. Wilson No. 2 5-yr CV precipitation 

# --------------------------------
# statistics for 5-yr cv

mtwilson_5yr_lm <- lm(x5yr_cv ~ year, data=mtwilson_precip)
summary(mtwilson_5yr_lm)
# p-value: 0.152 - NOT Significant

# --------------------------------
# Graph of Mt. Wilson 5-yr CV precipitation

mtwilson_5yr_graph <- ggplot(data=mtwilson_precip,
                                aes(x = year,
                                    y = x5yr_cv)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (year)",
       y="5 yr CV in annual growing season precipitation",
       title="Mt. Wilson No. 2") +
  scale_x_continuous(limits=c(1945, 2020),
                     breaks=seq(1945,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
                    "5yr_cv",
                    "mtwilson_5yr_cv_graph.png"))
  
mtwilson_5yr_graph

```


```{r}
# Mt. Wilson No. 2 Snowfall

mtwilson_snowfall <- read_csv(here::here("csv_files",
                                         "snowfall",
                                         "mtwilsonno2_snowfall.csv"))
# ------------------------------------

# Statistics of Mt. Wilson No. 2 snowfall

mtwilsonsnowfall_lm <- lm(total ~ year, data=mtwilson_snowfall)
summary(mtwilsonsnowfall_lm)

# p-value: 0.0001138 (p < 0.001) Significant

# -------------------------------------

# Graph of snowfall

mtwilson_snowfall_graph <- ggplot(data=mtwilson_snowfall,
                                  aes(x=year,
                                      y=total)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Year",
       y="Snowfall (inches)",
       title="Mt. Wilson No. 2") +
  scale_x_continuous(limits=c(1945, 2020),
                     breaks=seq(1945,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method='lm',
              formula= y~x,
              se=FALSE,
              color= "black",
              size=0.5) +
  annotate("text", x = 2005, y = 80, label = "p-value < 0.001, slope = -0.7182") +
  ggsave(here::here("report_graphs",
                    "snowfall",
                    "mtwilson_snowfall_graph.png"),
          height=5,
         width=7,
         units="in")
  
mtwilson_snowfall_graph


```

