---
title: "Palmdale Climate"
author: "Hannah Garcia-Wickstrum"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(here)
```

```{r}
# Palmdale Temperature: 1933-2019
# Number of Missing Years: 0

palmdale_temp <- read_csv(here::here("csv_files",
                                     "temperature",
                                     "palmdale.csv")) %>%
  clean_names()

# ----------------------------------------
# Statistics (linear regression (lm)) for mean, max, and min temperature in Palmdale

## Mean model (lm)
meantemp_lm <- lm(mean ~ year, data=palmdale_temp)
summary(meantemp_lm)
# p-value: 7.465e-10 = Significant

## Max model (lm)
maxtemp_lm <- lm(max ~ year, data=palmdale_temp)
summary(maxtemp_lm)
# p-value: 4.081e-06 = Significant

## Min model (lm)
mintemp_lm <- lm(min ~ year, data=palmdale_temp)
summary(mintemp_lm)
# p-value: 8.845e-11 = Significant

# ------------------------------------------

# Create graph of averages (mean, max, and min)

palmdale_temp <- palmdale_temp %>%
  pivot_longer('mean':'min',
               names_to = "temp_average",
               values_to = "value")

palmdale_temp_graph <- ggplot(data=palmdale_temp, 
                              aes(x=year, y=value, 
                                  col=temp_average)) +
  theme_minimal() +
  geom_line() +
  geom_point() +
  geom_smooth(data=palmdale_temp,
              method="lm", 
              se=FALSE,
              size=0.65) +
  labs(x="Year",
       y="Degrees Farenheit", 
       title="Palmdale") +
  theme(plot.title = element_text(hjust = 0.5), legend.position="none") +
  scale_x_continuous(limits=c(1930, 2020),
                     breaks=seq(1930,2020,10),
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(40,85),
                     breaks=seq(40,85,5),
                     expand=c(0,0)) +
  # scale_color_discrete(name=NULL,
  #                      labels= c("max",
  #                                "mean",
  #                                "min")) +
  annotate("text", x = 1968, y = 70,
           label = "mean: p-value < 0.001
           slope=0.04022",
           size=3) +
  annotate("text", x = 1968, y = 55,
           label = "min: p-value < 0.001
           slope=0.03306",
           size=3) +
  annotate("text", x = 1968, y = 82,
           label = "max: p-value < 0.001
           slope=0.03306",
           size=3) +
  ggsave(here::here("report_graphs",
                    "temperature",
                    "palmdale_temperature_graph.png"),
          height=5,
         width=7,
         units="in")

palmdale_temp_graph
```

```{r}
# Change in temperature
# Use this equation: (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)

# -----------------------------------
# Mean temperature change: 2.097196
# year 1: 1933
# final year: 2019

x_variable <- 0.024386
intercept <- 12.723140

palmdale_change_temp <- (((2019)*x_variable) + intercept) - (((1933)*x_variable) + intercept)
# 61.958474 - 59.861278
palmdale_change_temp 

# --------------------------------
# Max temperature change: 2.84316 

x_variable_max <- 0.03306
intercept_max <- 12.07135
max_temp_change <- (((2019)*x_variable_max) + intercept_max) - (((1933)*x_variable_max) + intercept_max)
max_temp_change

# -------------------------------
# Min temperature change: 4.110026

x_variable_min <- 0.047791
intercept_min <- -47.023461
min_temp_change <- (((2019)*x_variable_min) + intercept_min) - (((1933)*x_variable_min) + intercept_min)
min_temp_change
```



```{r}
# Palmdale Precipitation

# read in csv

palmdale_precip <- read_csv(here::here("csv_files",
                                       "precipitation",
                                       "palmdale_precip.csv"))

#------------------------------------

# Statistics for Palmdale Precipitation

palmdaleprecip_lm <- lm(annualgrowingseason ~ year, data = palmdale_precip)
summary(palmdaleprecip_lm)
# p-value: 0.2836 - NOT Significant

# -------------------------------------

# Palmdale Precipitation Graph

palmdale_precip_graph <- ggplot(data=palmdale_precip,
                                aes(x=year,
                                    y=annualgrowingseason)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (year)",
       y="Precipitation (inches)",
       title="Palmdale") +
  scale_x_continuous(limits=c(1945, 2020),
                     breaks=seq(1945,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
                    "precipitation",
                    "palmdale_precip_graph.png"))

palmdale_precip_graph

```

```{r}
# Palmdale 5-yr CV precipitation 

# --------------------------------
# statistics for 5-yr cv

palmdale_5yr_lm <- lm(x5yr_cv ~ year, data=palmdale_precip)
summary(palmdale_5yr_lm)
# p-value: 0.001735 - Significant

# --------------------------------
# Graph of Palmdale 5-yr CV precipitation

palmdale_5yr_graph <- ggplot(data=palmdale_precip,
                                aes(x = year,
                                    y = x5yr_cv)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (year)",
       y="5 yr CV in annual growing season precipitation",
       title="Palmdale") +
  scale_x_continuous(limits=c(1919, 2020),
                     breaks=seq(1919,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
   geom_smooth(method='lm',
              formula= y~x,
              se=FALSE,
              color= "black",
              size=0.5) +
  annotate("text", x = 1939, y = 1,
           label = "CV = 0.0023*(year) - 4.01345") +
  annotate("text", x = 1939, y = 0.95, 
           label = "p-value = 0.001735, R2=0.0903") +
  ggsave(here::here("report_graphs",
                    "5yr_cv",
                    "palmdale_5yr_cv_graph.png"),
          height=5,
         width=7,
         units="in")
  
palmdale_5yr_graph
```

```{r}
# Change in Precipitation CV
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1920
# final year: 2017

# -----------------------------------
# Change in CV: 0.222324

x_variable <- 0.002292
intercept <- -4.013449

cv_change <- (((2017)*x_variable) + intercept) - (((1920)*x_variable) + intercept)

cv_change
```


```{r}
# Palmdale Snowfall

# read in csv
palmdale_snow_2 <- read_csv(here::here("csv_files",
                                       "snowfall",
                                       "palmdale_edit.csv"))

# --------------------------------------
palm_snow_lm <- lm(annualgrowingseason ~ years, data=palmdale_snow_2)
summary(palm_snow_lm)
# p-value: 0.0377 - Significant
# x-variable: -0.03947
# Intercept: 79.02825

# --------------------------------------
palmsnow_graph <- ggplot(data=palmdale_snow_2,
                                aes(x=years,
                                    y=annualgrowingseason)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Year",
       y="Snowfall (inches)",
       title="Palmdale") +
  scale_x_continuous(limits=c(1945, 2020),
                     breaks=seq(1945,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method='lm',
              formula= y~x,
              se=FALSE,
              color= "black",
              size=0.5) +
  annotate("text", x = 2005, y = 17.5,
           label = "p-value = 0.0377, slope = -0.03947") +
  annotate("text", x = 2000, y = 16,
           label = "snowfall = -0.03947*(year) + 79.02825") +
  ggsave(here::here("report_graphs",
                    "snowfall",
                    "palmdale_snowfall_graph_take2.png"),
          height=5,
         width=7,
         units="in")

palmsnow_graph
```

```{r}
# Change in Snowfall
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1935
# final year: 2010

# -----------------------------------
# Change in CV: -2.96025

x_variable <- -0.03947
intercept <- 79.02825

snowfall_change <- (((2010)*x_variable) + intercept) - (((1935)*x_variable) + intercept)

snowfall_change
```

