---
title: "Pasadena"
author: "Hannah Garcia-Wickstrum"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(here)
```

```{r}
# Pasadena Temperature: 1909-2019
# Number of Missing Years: 0

pasadena_temp <- read_csv(here::here("csv_files",
                                     "temperature",
                                     "pasadena.csv"))

# -----------------------------------
# Statistics (linear regression (lm)) for mean, max, and min temperature in Pasadena

## Mean model (lm)
meantemp_lm <- lm(mean ~ year, data=pasadena_temp)
summary(meantemp_lm)
# stargazer(meantemp_lm, type = "text")
# p-value: < 2.2 x 10 ^-16 = Significant

## Max model (lm)
maxtemp_lm <- lm(max ~ year, data=pasadena_temp)
summary(maxtemp_lm)
# stargazer(maxtemp_lm, type ="text")
# p-value: < 2.2 x 10 ^-16 = Significant

## Min model (lm)
mintemp_lm <- lm(min ~ year, data=pasadena_temp)
summary(mintemp_lm)
# stargazer(mintemp_lm, type = "text")
# p-value: < 2.2 x 10 ^-16 = Significant
 
#------------------------------------
# Create graph of averages (mean, max, and min)

pasadena_temp_graph <- ggplot(data=pasadena_temp, aes(x=year)) +
  geom_line(aes(y=mean), 
            color="black") +
  geom_line(aes(y=max), 
            color="black") +
  geom_line(aes(y=min), 
            color="black") +
  geom_point(aes(y=mean), 
             color="black", 
             pch=18, size=1.5) +
  geom_point(aes(y=max), 
             color="darkred",
             pch=15, size=1.5) +
  geom_point(aes(y=min), 
             color="gold", 
             pch=17, size=1.5) +
  labs(x="Year",
       y="Degrees Farenheit", 
       title="Pasadena") +
  scale_x_continuous(limits=c(1908, 2020), 
                     breaks=seq(1908,2020,10), 
                     expand=c(0,1)) +
  scale_y_continuous(limits=c(45,85), 
                     breaks=seq(45,85,5), 
                     expand=c(0,0)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

pasadena_temp_graph
```

```{r}
# Change in temperature
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1909
# final year: 2019

# -----------------------------------
# Mean temperature change: 6.57041

x_variable_mean <- 0.059731
intercept_mean <- -53.040541

mean_temp_change <- (((2019)*x_variable_mean) + intercept_mean) - (((1909)*x_variable_mean) + intercept_mean)

mean_temp_change

# --------------------------------
# Max temperature change: 4.61945 

x_variable_max <- 0.041995 
intercept_max <- -5.343924
max_temp_change <- (((2019)*x_variable_max) + intercept_max) - (((1909)*x_variable_max) + intercept_max)
max_temp_change

# -------------------------------
# Min temperature change: 8.5437

x_variable_min <- 7.767e-02
intercept_min <-  -1.011e+02
min_temp_change <- (((2019)*x_variable_min) + intercept_min) - (((1909)*x_variable_min) + intercept_min)
min_temp_change
```



```{r}
# Pasadena Precipitation

pasadena_precip <- read_csv(here::here("csv_files",
                                       "precipitation",
                                       "pasadena_precip.csv"))
# ---------------------------------

# Statistics for Pasadena Precipitation

pasadenaprecip_lm <- lm(annualgrowingseason ~ year, data=pasadena_precip)
summary(pasadenaprecip_lm)
# p-value: 0.246 - NOT Significant

# -----------------------------------

# Graph for Pasadena Precipitation 

pasadena_precip_graph <- ggplot(data=pasadena_precip,
                                aes(x=year,
                                    y=annualgrowingseason)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (Year)",
       y="Precipitation (inches)",
       title="Pasadena") +
  scale_x_continuous(limits=c(1945, 2020),
                     breaks=seq(1945,2020,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggsave(here::here("report_graphs",
                    "precipitation",
                    "pasadena_precip_graph.png"))

pasadena_precip_graph

```

```{r}
## Pasadena 5-yr CV precipitation 

# --------------------------------
# Statistics for 5-yr cv

pasadena_5yr_lm <- lm(x5yr_cv ~ year, data=pasadena_precip)
summary(pasadena_5yr_lm)
# p-value: 1.106e-06 (p-value < 0.001) - Significant
# equation: CV = 0.0022*(year) - 3.97931
# Adjusted R2 = 0.2139

# --------------------------------
# Graph of Pasadena 5-yr CV precipitation

pasadena_5yr_graph <- ggplot(data=pasadena_precip,
                                aes(x = year,
                                    y = x5yr_cv)) +
  theme_minimal() +
  geom_point(color = "blue") +
  geom_line(color = "blue") + 
  labs(x="Growing Season (year)",
       y="5 yr CV in annual growing season precipitation",
       title="Pasadena") +
  scale_x_continuous(limits=c(1905, 2022),
                     breaks=seq(1905,2022,10),
                     expand=c(0,1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method='lm',
              formula= y~x,
              se=FALSE,
              color= "black",
              size=0.5) +
  annotate("text", x = 2000, y = 0.2,
           label = "CV = 0.0022*(year) - 3.97931") +
  annotate("text", x = 2000, y = 0.16,
           label = "p-value < 0.001, R2 = 0.2139") +
  ggsave(here::here("report_graphs",
                    "5yr_cv",
                    "pasadena_5yr_cv_graph.png"))
  
pasadena_5yr_graph
```

```{r}
# Change in Precipitation CV
# Use this equation: 
# (final year)*(X-Variable)+(Intercept)] - [(year 1)*(X-Variable)+(Intercept)
# year 1: 1909
# final year: 2019

# -----------------------------------
# Change in CV: 0.244574

x_variable <- 0.0022234
intercept <- -3.9793120

cv_change <- (((2019)*x_variable) + intercept) - (((1909)*x_variable) + intercept)

cv_change
```

